services:
  obsidian:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VITE_DEFAULT_IRC_SERVER: wss://${IRC_FQDN}
        VITE_DEFAULT_IRC_SERVER_NAME: ${NETWORK_NAME}
    image: obsidianirc:local
    container_name: obsidianirc
    restart: unless-stopped
    expose:
      - "80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.obsidian.rule=Host(`${WEB_FQDN}`)
      - traefik.http.routers.obsidian.tls=true
      - traefik.http.services.obsidian.loadbalancer.server.port=80
