services:
  obsidian:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obsidian-irc
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

# TODO - Add IRC daemon + backend etc
