FROM node:23-alpine AS builder

ARG VITE_DEFAULT_IRC_SERVER
ARG VITE_DEFAULT_IRC_SERVER_NAME
ARG VITE_DEFAULT_IRC_CHANNELS
ARG VITE_HIDE_SERVER_LIST
ARG VITE_TRUSTED_MEDIA_URLS
ARG VITE_DEFAULT_OAUTH_PROVIDER_LABEL
ARG VITE_DEFAULT_OAUTH_ISSUER
ARG VITE_DEFAULT_OAUTH_CLIENT_ID
ARG VITE_DEFAULT_OAUTH_SCOPES
ARG VITE_DEFAULT_OAUTH_REDIRECT_URI
ARG VITE_DEFAULT_OAUTH_TOKEN_KIND
ARG VITE_DEFAULT_OAUTH_SERVER_PROVIDER
ARG VITE_DEFAULT_OAUTH_AUTHORIZE_URL
ARG VITE_DEFAULT_OAUTH_TOKEN_URL

ENV VITE_DEFAULT_IRC_SERVER=$VITE_DEFAULT_IRC_SERVER
ENV VITE_DEFAULT_IRC_SERVER_NAME=$VITE_DEFAULT_IRC_SERVER_NAME
ENV VITE_DEFAULT_IRC_CHANNELS=$VITE_DEFAULT_IRC_CHANNELS
ENV VITE_HIDE_SERVER_LIST=$VITE_HIDE_SERVER_LIST
ENV VITE_TRUSTED_MEDIA_URLS=$VITE_TRUSTED_MEDIA_URLS
ENV VITE_DEFAULT_OAUTH_PROVIDER_LABEL=$VITE_DEFAULT_OAUTH_PROVIDER_LABEL
ENV VITE_DEFAULT_OAUTH_ISSUER=$VITE_DEFAULT_OAUTH_ISSUER
ENV VITE_DEFAULT_OAUTH_CLIENT_ID=$VITE_DEFAULT_OAUTH_CLIENT_ID
ENV VITE_DEFAULT_OAUTH_SCOPES=$VITE_DEFAULT_OAUTH_SCOPES
ENV VITE_DEFAULT_OAUTH_REDIRECT_URI=$VITE_DEFAULT_OAUTH_REDIRECT_URI
ENV VITE_DEFAULT_OAUTH_TOKEN_KIND=$VITE_DEFAULT_OAUTH_TOKEN_KIND
ENV VITE_DEFAULT_OAUTH_SERVER_PROVIDER=$VITE_DEFAULT_OAUTH_SERVER_PROVIDER
ENV VITE_DEFAULT_OAUTH_AUTHORIZE_URL=$VITE_DEFAULT_OAUTH_AUTHORIZE_URL
ENV VITE_DEFAULT_OAUTH_TOKEN_URL=$VITE_DEFAULT_OAUTH_TOKEN_URL

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
